proiectcolectiv/proiectcolectiv/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('web.urls')),
]

proiectcolectiv/web/urls.py
from django.conf.urls import url

from .job import *
from .views import *
from .account import *




urlpatterns = [


    #Account-related
    url(r'^logout$', log_out, name='log out'),
    url(r'^account/edit$', edit_ajax, name='edit profile ajax'),
    url(r'^account/edit/addinterest$', edit_interest_ajax, name='edit interest ajax'),
    url(r'^account/edit/deleteinterest$', delete_interest_profile, name='delete interest profile'),
    url(r'^account/edit/checks$', edit_checks_ajax, name='edit checks ajax'),
    url(r'^account/login$', auth_ajax, name='authenticate'),
    url(r'^account/register$', reg_ajax, name='register'),

    #Profile-related
    url(r'^profile/(?P<username>[^\/]*)$', profile, name='view profile'),
    url(r'^profile/(?P<username>.*)/reviews$', reviews, name='user reviews'),
    url(r'^edit$', edit_profile, name='edit profile'),
    url(r'^edit/addinterest$', edit_interest_profile, name='edit interest profile'),
    url(r'^seekers$', seekers, name='view job seekers'),
    url(r'^handle_notification/(?P<notification_id>.*)$', handle_notification, name='handle notification'),
    url(r'^notifications$', notifications, name='notifications'),

    #Job-related
    url(r'^jobs$', jobs, name='view jobs'),
    url(r'^job/add$', add_ajax, name='add job ajax'),
    url(r'^job/edit$', edit_job_ajax, name='edit job ajax'),
    url(r'^job_add$', job_add, name='job add'),
    url(r'^job/(?P<job_id>[0-9]+)$', job_detail, name='job detail'),
    url(r'^job/(?P<job_id>[0-9]+)/edit$', job_edit, name='job edit'),
    url(r'^job/(?P<job_id>[0-9]+)/delete$', job_delete, name='job delete'),
    url(r'^job/(?P<job_id>[0-9]+)/apply$', job_apply, name='choose apply'),
    url(r'^job/(?P<job_id>[0-9]+)/choose$', job_choose_applicant, name='choose applicant'),
    url(r'^job/(?P<job_id>[0-9]+)/deselect$', job_deselect_applicant, name='deselect applicant'),

    #Profile-related
    url(r'^profile/(?P<username>.*)$', profile, name='view profile'),
    url(r'^edit$', edit_profile, name='edit profile'),
    url(r'^my_jobs$', edit_my_jobs, name='edit my jobs'),
    url(r'^edit/addinterest$', edit_interest_profile, name='edit interest profile'),
    url(r'^seekers$', seekers, name='view job seekers'),
    url(r'^handle_notification/(?P<notification_id>.*)$', handle_notification, name='handle notification'),
    url(r'^notifications$', notifications, name='notifications'),
    url(r'^job/(?P<job_id>[0-9]+)/review$', job_review, name='job review'),
    url(r'^job/review/send$', job_review_send_ajax, name='job review send'),

    #Keep this last
    url(r'$', home),
]

proiectcolectiv/web/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from django.db.models import CASCADE, DecimalField, FloatField, DateField
from django.db.models import ForeignKey
from django.db.models import IntegerField, CharField, DateTimeField, BooleanField, OneToOneField, ManyToManyField
import django.forms


class Category(models.Model):
    name = CharField(max_length=100)
    subscribers=ManyToManyField('Profile', through='Interest')

    @classmethod
    def create(cls, name):
        category = cls(name=name)
        return category

    def __str__(self):
        return self.name


class Location(models.Model):
    name = CharField(max_length=50)

    def __str__(self):
        return self.name


class Profile(models.Model):
    user = OneToOneField(User, on_delete=CASCADE)
    is_offering = BooleanField(default=False)
    is_searching = BooleanField(default=False)
    hide_email_for_strangers = BooleanField(default=False)
    interests = ManyToManyField(Category, through='Interest')
    notifications = ManyToManyField('Job', through='Notification')
    location = ForeignKey(Location, default=None, null=True)

    def __str__(self):
        return str(self.user.username)


class Job(models.Model):
    PER_TIME_CHOICES = (('d','day'), ('m','month'),('w','week'),('t','total'),)
    PER_COST_CHOICES = (('h','hour'), ('d','day'), ('m','month'),('w','week'),('t','total'),)
    name = CharField(max_length=100)
    description = CharField(max_length=500)
    user = ForeignKey(User, on_delete=CASCADE)

    publish_date = DateTimeField(auto_now_add=True, null=True)
    start_date = DateField(null=True)
    end_date = DateField(null=True)

    location = ForeignKey(Location)

    number_of_hours = IntegerField()
    per_time = CharField(max_length=10, choices=PER_TIME_CHOICES)

    cost_of_services = FloatField()
    per_cost = CharField(max_length=10, choices=PER_COST_CHOICES)

    requirements = CharField(default='', max_length=500)
    category = ForeignKey(Category, on_delete=CASCADE)

    applicants = ManyToManyField(Profile, through='Application')
    user_chosen = ForeignKey(Profile, related_name='user_chosen', null=True)

    is_available = BooleanField(default=True)
    average_applicant_rating = FloatField(null=True)
    average_employer_rating = FloatField(null=True)

    @classmethod
    def create(cls, name, description, user,
               publish_date, start_date, end_date,
               location, number_of_hours, per_time, cost_of_services, per_cost,
               requirements, category):
        job = cls(name=name, description=description, user=user,
                  publish_date=publish_date, start_date=start_date, end_date=end_date,
                  location=location, number_of_hours=number_of_hours, per_time=per_time,
                  cost_of_services=cost_of_services, per_cost=per_cost,
                  requirements=requirements, category=category)
        return job

    def __str__(self):
        return 'ID: ' + str(self.id) + ' ' + str(self.name)


class Notification(models.Model):
    user = ForeignKey(Profile)
    job = ForeignKey(Job)
    receive_date = DateTimeField(auto_now_add=True, null=True)
    is_read = BooleanField(default=False)
    notification_text = CharField(max_length=500)

    def __str__(self):
        return ('Unread' if not self.is_read else 'Read') + ' :' + str(self.notification_text)


class Application(models.Model):
    user = ForeignKey(Profile)
    job = ForeignKey(Job)
    apply_date = DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.user.user.username + '\'s application for ' + self.job.user.username + '\'s job named ' + self.job.name


class Interest(models.Model):
    pay = BooleanField(default=False)
    category = ForeignKey(Category)
    profile = ForeignKey(Profile)

    @classmethod
    def create(cls, pay, category, profile):
        interest = cls(pay=pay, category=category, profile=profile)
        return interest

    def __str__(self):
        return self.profile.user.username + '\'s ' + ('voluntary' if not self.pay else 'paid') + ' interest in ' + self.category.name

class Review(models.Model):
    STAR_CHOICES = (
        (0, '---'),
        (1, '*'),
        (2, '**'),
        (3, '***'),
        (4, '****'),
        (5, '*****')
    )

    user_reviewed = ForeignKey(User, related_name='reviewed')
    user_reviewing = ForeignKey(User, related_name='reviewing')
    job = ForeignKey(Job)
    stars = IntegerField(choices=STAR_CHOICES)
    comment = CharField(max_length=300)
    employer_review = BooleanField(default=False)
    timestamp = DateTimeField(auto_now_add=True, null=True)

    @classmethod
    def create(cls, user_reviewing, user_reviewed, job, stars, timestamp, comment, employer_review):
        review = cls(user_reviewing=user_reviewing, user_reviewed=user_reviewed, job=job, stars=stars, timestamp=timestamp, comment=comment, employer_review=employer_review)
        return review

    def __str__(self):
        return self.user_reviewing.username + '\'s review on ' + self.user_reviewed.username + ' as an ' + ('applicant' if not self.employer_review else 'employer') + ' is ' + str(self.stars) + ' stars'

proiectcolectiv/web/templates/edit.html
<!-- Meta stuff, javascript, css etc -->
{% load static %}
<link rel="stylesheet" type='text/css' href="{% static 'style/edit.css' %}"/>

{% load static %}
<script type="text/javascript" src="{% static 'script/jquery-3.2.1.min.js' %}"></script>
{% load static %}
<script type="text/javascript" src="{% static 'script/edit.js' %}"></script>
{% load static %}
<script type="text/javascript" src="{% static 'script/flash-service.js' %}"></script>
{% load static %}
<script type="text/javascript" src="{% static 'script/menu.js' %}"></script>

<title>Profile</title>

<!-- Content goes down here -->
<div class = "form_container">
    <div class = "form">
        <div class = "form_content">
            <form id="edit_form" action="/account/edit" method="POST">
                {% csrf_token %}
                <br>
                <b>First Name:</b> {{ form.first_name }}<br>
                <div id='edit-firstname-error' class='flash-container'></div>
                <br>
                <b>Last Name:</b> {{ form.last_name }}<br>
                <div id='edit-lastname-error' class='flash-container'></div>
                <br>
                <b>Email:</b> {{ form.email }}<br>
                <div id='edit-email-error' class='flash-container'></div>
                <br>
                <b>Location: </b> {{ interests_form.location }}<br>
                <br><br>
                <b>New password (optional):</b> {{ form.new_password }}<br>
                <div id='edit-pass-error' class='flash-container'></div>
                <br>
                <b>Confirm new password:</b> {{ form.new_password_confirm }}<br>
                <div id='edit-pass-confirm-error' class='flash-container'></div>
                <br>
                <b>Your current password:</b> {{ form.old_password }}<br>
                <div id='edit-confirm-error' class='flash-container'></div>
            </form><br>
            <input class="inputbutton" type="submit" value="Save changes" id="edit_button">
            <br>

            <a style="display:none" id="location_hidden">{{location_id}}</a>


            <br>
            <div >
                <a id="is_searching" style="display: none;">{{profile.is_searching}}</a>
                <form id="jobs-general">
                    {% csrf_token %}
                    <label class="checkbox-label">Interested in jobs</label>
                    <input class="checkbox-input" id="interested-checkbox" type="checkbox" name="interest"> <br>
                    <span class="checkmark"></span>
                </form>
            </div>
            <br>
            <div >
                <a id="is_offering" style="display: none;">{{profile.is_offering}}</a>
                <form id="aplicants-general">
                    {% csrf_token %}
                    <label class="checkbox-label">Interested in applicants</label>
                    <input class="checkbox-input" id="aplicants-checkbox" type="checkbox" name="interest"> <br>
                    <span class="checkmark"></span>

                </form>
            </div>
            <form id="edit_interest_form" action="/account/edit/addinterest" method="POST">
                {% csrf_token %}
                <br>
                <b>Interests:</b> {{ interests_form.interests }}<br><br>
                <b>Voluntary:</b> <input class="checkbox-input" id="pay-interest" type="checkbox" name="interest"> <span class="checkmark"></span> <br><br>
                <div id='edit-interests-error' class='flash-container'></div>
            </form>
            <input class="inputbutton" type="submit" value="Add interest" id="edit_interest_button">
            {% for interest in profile.interests.all %}
                 <form action="/account/edit/deleteinterest" method="POST">
                {% csrf_token %}
                     <input class="hidden_input" type="hidden" name="interest" value="{{interest.id}}">
                     <p>
                         {{interest.name}}
                     </p>
                     <input class="deletebutton" type="submit" value="Delete interest" id="delete_interest_button">


            </form>

            {% endfor %}
        </div>
    </div>
</div>
    

proiectcolectiv/web/templates/home.html
<!-- Meta stuff, javascript, css etc -->

<title>Home</title>
{%load static %}
<script type="text/javascript" src="{% static 'script/jquery-3.2.1.min.js' %}"></script>
{% load static %}
<link rel="stylesheet" type='text/css' href="{% static 'style/home.css' %}"/>
{% load static %}
<script type="text/javascript" src="{% static 'script/home.js' %}"></script>

    <div class="slideshow_container">
        <div class="slide">
            <div class="numberOnSlide">1/3</div>
            <div class="slide_content">
                <div id="right_content_slide1">
                    <img id="image1"  src="{% static 'style/img/home1.jpg' %}" >
                    <img id="image2" src="{% static 'style/img/home2.jpg' %}" >
                    <img id="image3" src="{% static 'style/img/home3.jpg' %}" >
                    <img id="image4" src="{% static 'style/img/home4.jpg' %}" >
                </div>
                <div id="left_content_slide1">
                    <h3>About us</h3>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut vel ex eget ligula finibus bibendum. In a auctor dolor. Nunc blandit risus varius lectus iaculis scelerisque. Praesent laoreet et urna at venenatis. Curabitur vitae interdum justo, vel egestas nisl. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis orci urna. Donec quis blandit ligula. Suspendisse ut dapibus turpis, vel elementum arcu. Pellentesque vel pellentesque elit. Quisque eu ipsum posuere, tempus purus eget, finibus magna.

                        Aliquam a aliquam leo. Cras dictum finibus ex id luctus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vestibulum aliquam elementum consequat. Morbi cursus metus a erat hendrerit, nec porttitor urna ultricies. Sed eleifend elit elit, vel ornare elit imperdiet sed. Sed pharetra nibh in arcu condimentum vulputate. Fusce convallis orci in lectus dapibus rhoncus. Sed sit amet lacus euismod, eleifend ex condimentum, rhoncus nulla. Praesent at bibendum justo. Aenean malesuada lacus sit amet risus interdum tempus. Integer ac varius felis.
                    </p>
                </div>
            </div>
        </div>

        <div class="slide">
            <div class="numberOnSlide">2/3</div>
             <div class="slide_content">
                 <div id="right_content_slide2">
                     <h3>Our team</h3>
                    <p>
                        Aliquam malesuada leo sapien, mattis tempor velit semper eget. Nullam vel dui et diam vehicula lacinia. Sed euismod tincidunt iaculis. Nam fermentum scelerisque sem, eget rhoncus ex faucibus id. Maecenas fringilla, risus sed fermentum fringilla, augue ante cursus ipsum, non rutrum orci leo sit amet enim
                        Aliquam erat volutpat. Aliquam sit amet velit venenatis, laoreet nunc eget, viverra sem. Proin congue metus quam, eu fermentum velit malesuada vestibulum. Nunc semper vulputate neque. Phasellus eget pulvinar sapien. Aenean eros purus, tristique at enim sit amet, condimentum dignissim orci. In hac habitasse platea dictumst. Maecenas turpis orci, tempor non sem ac, pulvinar porta nibh. Cras mattis odio volutpat orci pellentesque volutpat. Aenean in nulla vitae sem fringilla tristique id vitae quam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi fermentum ligula metus, at mattis odio ullamcorper et. Nunc pulvinar ac erat quis efficitur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sit amet mauris eros.
                    </p>
                 </div>
                 <div id="left_content_slide2">
                    <img id="image5" src="{% static 'style/img/home5.jpg' %}">
                 </div>
            </div>

        </div>

        <div class="slide">
            <div class="numberOnSlide">3/3</div>
             <div class="slide_content">
                 <div id="content_slide3">
                    <h3>Information corner</h3>
                    <p>
                        Nulla rutrum ex vel dignissim egestas. Nam suscipit vehicula sapien at feugiat. Ut arcu enim, tincidunt at dui eget, sodales laoreet sem. In dapibus sit amet sapien eget elementum. Fusce fermentum felis tellus, eget pulvinar nisl dapibus in. Donec lobortis elementum elit eget feugiat. Aliquam vel eros tellus. Quisque quis enim a quam efficitur vulputate porta ut ligula. Ut eu ante congue, pulvinar nulla et, tempus lacus. Proin ut justo quis nunc tempor facilisis. Donec a nibh massa. Quisque euismod nunc elementum urna ornare, sit amet interdum libero tristique. Nunc sit amet tincidunt massa, suscipit pulvinar dui. Maecenas eget ante suscipit, facilisis ipsum in, feugiat nisi.
                        Phasellus sed ligula a lorem elementum mollis. In hac habitasse platea dictumst. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi fringilla lorem neque, non fermentum elit maximus eu. Donec est tortor, dignissim eget ante et, malesuada congue sem. Nam in porttitor mi, in vehicula est. Quisque eget sem vitae sapien aliquet lacinia vel in purus. In hac habitasse platea dictumst. Nam at mi eget justo facilisis ornare nec vitae lacus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque eu lectus nisl. Vestibulum tempor erat odio, vel rutrum magna euismod id.
                        Donec ac lectus at massa eleifend scelerisque. Donec quis mi ut mauris facilisis vehicula eu non arcu. Maecenas rhoncus eleifend arcu. Nunc vitae tempus metus. Nullam consectetur porta tellus, at lacinia lorem convallis eu. Phasellus mi neque, laoreet vitae elit a, tincidunt scelerisque ex. Proin ut finibus justo. Morbi ac arcu lectus. Vestibulum dictum justo gravida, maximus neque eu, lobortis sapien.
                    </p>
                 </div>
            </div>
        </div>

        <a class="prev" >&#10094;</a>
        <a class="next" >&#10095;</a>
        <br>
        <div class="dot_container">
          <span id="slide1" class="dot" ></span>
          <span id="slide2" class="dot" ></span>
          <span id="slide3" class="dot" ></span>
        </div>
    </div>

proiectcolectiv/web/templates/job_add.html
{% load static %}
<link rel="stylesheet" type='text/css' href="{% static 'style/job_add.css' %}"/>
{% load static %}
<link rel="stylesheet" type='text/css' href="{% static 'style/flash-service.css' %}"/>
{% load static %}
<link rel="stylesheet" type='text/css' href="{% static 'jquery-ui-1.12.1/jquery-ui.min.css' %}"/>

{% load static %}
<script type="text/javascript" src="{% static 'script/jquery-3.2.1.min.js' %}"></script>
{% load static %}
<script type="text/javascript" src="{% static 'script/job_add.js' %}"></script>
{% load static %}
<script type="text/javascript" src="{% static 'script/flash-service.js' %}"></script>
{% load static %}
<script type="text/javascript" src="{% static 'script/menu.js' %}"></script>
{%load static %}
<script type="text/javascript" src="{% static 'jquery-ui-1.12.1/jquery-ui.min.js' %}"></script>



<title>Add Job</title>

<div class = "form_container">
    <div class = "form">
        <div class = "form_content">
            <form id='add_form' action='/job/add' method="POST">
                {% csrf_token %}

                <b>Title:</b> {{ form.title }}<br>
                <div id="add-title-error" class='flash-container'></div>

                <b>Description:</b> {{ form.description }}<br>
                <div id='add-description-error' class='flash-container'></div>

                <b>Category:</b> {{ form.category }}<br>
                <div id='add-category-error' class='flash-container'></div>

                <b>Start:</b> {{ form.start_date }}<br>
                <div id='add-start-error' class='flash-container'></div>

                <b>End:</b> {{ form.end_date }}<br>
                <div id='add-end-error' class='flash-container'></div>


                <b>Number of hours :</b> {{ form.number_of_hours }}
                <div id="add-number_of_hours-error" class='flash-container'></div>
                <b>per :</b> {{ form.per_time }} <br><br>

                <b>Voluntary:</b> <input class="checkbox-input" id="pay-interest" type="checkbox" name="interest"> <span class="checkmark"></span> <br><br>
                <b>Cost of services:</b> {{ form.cost_of_services }}
                <div id='add-cost_of_services-error' class='flash-container'></div>
                <b>per:</b> {{ form.per_cost }}<br><br>

                <b>Location:</b> {{ form.location }}<br>
                <div id='add-location-error' class='flash-container'></div>

                <b>Requirements:</b> {{ form.requirements }}<br>
                <div id='add-requirements-error' class='flash-container'></div>


                <br>
            </form>



            <input class="inputbutton" type="submit" value="Add job" id="add_button">

        </div>
    </div>
</div>

proiectcolectiv/web/templates/job_detail.html
<title>Job Detail</title>
{% load mathfilters %}
{% load list_utils %}
{% load static %}
<link rel="stylesheet" type='text/css' href="{% static 'style/job_detail.css' %}"/>
{% load static %}
<link rel="stylesheet" type='text/css' href="{% static 'style/table.css' %}"/>

<body>
    <div class="jobDetail">
        <form action="/job/{{job.id}}/edit" method="get">
            <input type="submit" id="edit_job_button" value="Edit">
        </form>
        <form action="/job/{{job.id}}/delete" method="get">
            <input type="submit" id="delete_job_button" value="Delete">
        </form>
        <div class="jobTitle">{{job.name}}</div>
        <br>
        <div class="jobDescr">{{job.description}}</div>
        <br>
        <div><b>Posted by: </b> <a href="/profile/{{job.user.username}}">{{job.user.username}}</a> on {{job.publish_date}}</div>
        <br>
        {% if job.user.average_employer_rating %}
            <div><b>Average rating: </b> {{job.user.average_employer_rating}}</div>
            <br>
        {% endif %}
        <div> <b>Category: </b> {{job.category}}</div>
        <br>
        <div> <strong>Working hours per {{job.get_per_time_display}}:</strong> {{job.number_of_hours}}</div>

        <br>
        <div> <strong>Payment:</strong> {% if job.cost_of_services == 0 %} Voluntary {% else %} {{job.cost_of_services}} RON per {{job.get_per_cost_display}}. {% endif %}</div>
        <br>
        <div> <b>Requirements: </b> {{job.requirements}}</div>
        <br>
        <div> <b>Location: </b> {{job.location}}</div>
        <br>
        <div> <b>Start date: </b> {{job.start_date}}</div>
        <br>
        <div> <b>End date:</b>{{job.end_date}}</div>
        {% if reviewable %}
            <a href="/job/{{job.id}}/review"> Write a review for
                {% if user.id is job.user.id %}
                    your selected applicant
                {% else %}
                    your employer
                {% endif %}
                here
            </a>
            <br>
        {% endif %}
        {% if user.is_authenticated %}
            {% if job.user.id == request.user.id %}
                {% if job.applicants.all|length %}
                    <table class = "data-table">
                        <thead>
                            <tr class="data-tr">
                                <th class="data-th">Applicant</th>
                                <th class="data-th">Date</th>
                                <th class="data-th">Select</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for applicant in job.application_set.all %}
                                <tr class="data-tr">
                                    <td class="data-td">
                                        <a href="/profile/{{applicant.user.user.username}}">
                                            {% if applicant.user.user.first_name|length or applicant.user.user.last_name|length %}
                                                {{applicant.user.user.first_name}} {{applicant.user.user.last_name}}
                                            {% else %}
                                                {{applicant.user.user.username}}
                                            {% endif %}
                                        </a>
                                    </td>
                                    <td class="data-td">{{applicant.apply_date}}</td>
                                    <td class="data-td">
                                        {% if job.user_chosen %}
                                            {% if job.user_chosen.id == applicant.user.id %}
                                                <form action="/job/{{job.id}}/deselect" method="POST">
                                                    {% csrf_token %}
                                                    <input type="hidden" name="user" value="{{applicant.user.id}}">
                                                    <p class="selected">Selected </p>   <input type="submit" value="X">
                                                </form>

                                            {% endif %}
                                        {% else %}
                                            <form action="/job/{{job.id}}/choose" method="POST">
                                                {% csrf_token %}
                                                <input type="hidden" name="user" value="{{applicant.user.id}}">
                                                <input type="submit" value="Accept">
                                            </form>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {{ paged }}
                {% else %}
                    <p>No applicants.</p>
                {% endif %}

            {% else %}
                {% if request.user.profile not in job.applicants.all %}
                    {% if job.applicants.all|length == 0 %}
                        <p>This job looks fresh!</p>
                    {% elif job.applicants.all|length == 1 %}
                        <p>One user applied for this job.</p>
                    {% else %}
                        <p>{{job.applicants.all|length}} users applied for this job</p>
                    {% endif %}
                        <form  action="/job/{{job.id}}/apply" method="POST" id="formApply">
                            {% csrf_token %}
                            <input type="hidden" name="user" value="{{request.user.id}}">
                           <input type="submit" value="Apply">
                        </form>
                {% endif %}
                {% if request.user.profile in job.applicants.all %}
                     {% if job.applicants.all|length == 0 %}
                        <p>This job looks fresh!</p>
                     {% elif job.applicants.all|length == 1 %}
                        <p>You applied for this job.</p>
                     {% else %}
                        <p>You and {{ job.applicants.all|length|sub:1 }} other users applied for this job</p>
                     {% endif %}
                {% endif %}
                {% if job.user_chosen %}
                    {% if job.user_chosen.user == request.user %}
                        <p>You were selected for this job!</p>
                    {% else %}
                        <p>The user selected another applicant.</p>
                    {% endif %}
                {% endif %}

            {% endif %}
        {% endif %}
    </div>
</body>

proiectcolectiv/web/templates/job_edit.html
{% load static %}
<link rel="stylesheet" type='text/css' href="{% static 'style/job_edit.css' %}"/>
{% load static %}
<link rel="stylesheet" type='text/css' href="{% static 'style/flash-service.css' %}"/>
{% load static %}
<link rel="stylesheet" type='text/css' href="{% static 'jquery-ui-1.12.1/jquery-ui.min.css' %}"/>

{% load static %}
<script type="text/javascript" src="{% static 'script/jquery-3.2.1.min.js' %}"></script>
{% load static %}
<script type="text/javascript" src="{% static 'script/job_edit.js' %}"></script>
{% load static %}
<script type="text/javascript" src="{% static 'script/flash-service.js' %}"></script>
{% load static %}
<script type="text/javascript" src="{% static 'script/menu.js' %}"></script>
{%load static %}
<script type="text/javascript" src="{% static 'jquery-ui-1.12.1/jquery-ui.min.js' %}"></script>

<title>Edit Job</title>

<div class = "form_container">
    <div class = "form">
        <div class = "form_content">
            <form id='update_form' action='/job/edit' method="POST">
                {% csrf_token %}

                <b>Title:</b> {{ form.title }}<br>
                <div id="add-title-error" class='flash-container'></div>

                <b>Description:</b> {{ form.description }}<br>
                <div id='add-description-error' class='flash-container'></div>

                <b>Category:</b> {{ form.category }}<br>
                <div id='add-category-error' class='flash-container'></div>

                <b>Start:</b> {{ form.start_date }}<br>
                <div id='add-start-error' class='flash-container'></div>

                <b>End:</b> {{ form.end_date }}<br>
                <div id='add-end-error' class='flash-container'></div>


                <b>Number of hours :</b> {{ form.number_of_hours }}
                <div id="add-number_of_hours-error" class='flash-container'></div>
                <b>per :</b> {{ form.per_time }} <br><br>

                <b>Voluntary:</b> <input class="checkbox-input" id="pay-interest" type="checkbox" name="interest"> <span class="checkmark"></span> <br><br>
                <b>Cost of services:</b> {{ form.cost_of_services }}
                <div id='add-cost_of_services-error' class='flash-container'></div>
                <b>per:</b> {{ form.per_cost }}<br><br>

                <b>Location:</b> {{ form.location }}<br>
                <div id='add-location-error' class='flash-container'></div>

                <b>Requirements:</b> {{ form.requirements }}<br>
                <div id='add-requirements-error' class='flash-container'></div>


                <br>
            </form>



            <input class="inputbutton" type="submit" value="Update job" id="update_button">

        </div>
    </div>
</div>

proiectcolectiv/web/templates/template.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<link rel="stylesheet" type='text/css' href="{% static 'style/template.css' %}"/>
<head>
    <meta charset="UTF-8">
</head>
<body>
    {{  menu }}
    <div id = "content-wrapper">
        {{ content }}
    </div>
</body>
</html>